services:

  mysql:
    image: mysql:8.4
    container_name: hotel-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  backend:
    build: .
    image: hotel-backend:latest
    container_name: hotel-backend

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    image: hotel-frontend:latest
    container_name: hotel-frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

volumes:
  mysql_data:
